name: Integracao Continua

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f "Teia De Mistério - Jogo/requirements.txt" ]; then pip install -r "Teia De Mistério - Jogo/requirements.txt"; fi

    - name: Run Python tests
      run: |
        cd "Teia De Mistério - Jogo"
        python test_script.py
